### ISSUE TITLE
about the worldview problem of some countries

### ISSUE THREAD

**Issue by onrcrpk** [ngnijland/highlight-countries-mapbox#1]
Hello, 
Opacity is not working in those countries that have a conflict area—for example, Serbia. If you add Serbia to your map and try to opacity 0.5, it doesn't work because it puts multiple layers on top of each other, and the opacity becomes 1. And it looks different than other countries.

**Comment by ngnijland** [comment]
Hi @onrcrpk 

Thanks for having a look at this repository!

I see what you mean there, but I do think the opacity works. Let me explain. The tileset used in this example (Mapbox countires v1 created by Mapbox) gives color codes to every country. These codes range from 1 to 6. My guess is that Mapbox already adjusts the opacity based on these color codes.

Check this screenshot of Italy and Serbia next to each other:
![Screenshot 2022-07-27 at 07 59 49](https://user-images.githubusercontent.com/4727742/181172496-aa4fe359-c6bd-419f-86f2-adbabb02e49a.png)

The layer is added with the following config:

```javascript
      map.addLayer(
        {
          id: 'country-boundaries',
          source: {
            type: 'vector',
            url: 'mapbox://mapbox.country-boundaries-v1',
          },
          'source-layer': 'country_boundaries',
          type: 'fill',
          paint: {
            'fill-color': '#d2361e',
            'fill-opacity': 0.4,
          },
        },
        'country-label'
      );
```

As you can see the fill color that masks Serbia is a bit opaque. The mask over Italy is far less opaque. Serbia is marked with color group 3 and Italy with color group 6.

I'm not sure if there is a possibility to even out these color groups or overwrite their colors. I use this on my website and the difference in colors over there is fine for me.

Sorry that I can't give you a solution, but hopefully my explanation clears things up a bit!

**Comment by onrcrpk** [comment]
Hi @ngnijland ,
My problem was exactly that. I was working on a similar project, and if I add Serbia, it has different opacity than other cities, and it looks like Serbia has another meaning which is not.

The same issue also here:  https://docs.mapbox.com/data/tilesets/reference/mapbox-countries-v1/ 

I think it is because these countries have disputed areas. The solution might be there, but I am new to coding and trying to discover it. 

The only solution, for now, is using all countries opacity 1. otherwise, my map tells a different story than I want.

**Comment by ghost** [comment]
I had a look through the docs and tested some stuff and I think I've got an answer for you:

The tileset shows the map with all the different worldviews (china sees the world differently than the USA for example 😅). Because of that it renders multiple layers over each other on some countries. The solution is to filter away all worldviews except for one. Try to replace the `map.filter` in my example code with the following code:

```javascript
      map.setFilter(
        'country-boundaries',
        [
          'all',
          ['match', ['get', 'worldview'], ['all', 'US'], true, false],
          ['match', ['get', 'iso_3166_1_alpha_3'], ['NLD', 'ITA', 'SRB'], true, false]
        ]
      );
```

In this example the second filter row filters the worldview to only the USA world view. I tested this out and for me it looked like the countries are masked in the same color!

You can find more info about the world view stuff here: https://docs.mapbox.com/help/glossary/worldview/

**Comment by ghost** [comment]
I see you have a master of science in geo informatics, so you probably understand the worldview part better than me 😅😂 I hope the coding example helps you out though!

**Comment by onrcrpk** [comment]
Yay! It is working now, so I don't have to keep it full opacity :)

Haha, yes, I figured out the problem but implementing the code was not easy :) The differences are also shown here: https://docs.mapbox.com/mapbox-gl-js/example/toggle-worldviews/

**Comment by ngnijland** [comment]
Nice! Interesting how those views differ per country/part of the world.

Since this answers your question I'll close this issue for now. Feel free to reopen or open another issue if you have more questions.

Also, I'm interested in what you're building if you're able to please share what you're building here or on twitter!
